package pt.ulisboa.tecnico.sdis.id.ws.it;

import org.junit.Test;

import pt.ulisboa.tecnico.sdis.id.ws.UserDoesNotExist_Exception;

// classes generated by wsimport from WSDL

/**
 * Test suite
 */
public class RemoveUserIT extends AbstractIdIT {

    // tests
    // assertEquals(expected, actual);

    // public void removeUser(
    // RemoveUser parameters)
    // throws UserDoesNotExist {

    @Test(expected = UserDoesNotExist_Exception.class)
    public void test() throws Exception {
        // assumes user carla exists
        final String user = "carla";

        // remove user
        ID_CLIENT.removeUser(user);

        // should throw exception because user should no longer exist
        ID_CLIENT.removeUser(user);
    }

    @Test(expected = UserDoesNotExist_Exception.class)
    public void testUserDoesNotExist() throws Exception {
        ID_CLIENT.removeUser("userthatdoesnotexist");
    }

    @Test(expected = UserDoesNotExist_Exception.class)
    public void testUserNull() throws Exception {
        ID_CLIENT.removeUser(null);
    }
    
    @Test(expected = UserDoesNotExist_Exception.class)
    public void testUserEmpty() throws Exception {
        ID_CLIENT.removeUser("");
    }

}
